// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkVqURztu8TTZdhHgQj15GNw1DVhOivkk',
    appId: '1:734003181340:web:9430c3bdfb4f4c5e9eecd9',
    messagingSenderId: '734003181340',
    projectId: 'raccoon-doctor-3f2e3',
    authDomain: 'raccoon-doctor-3f2e3.firebaseapp.com',
    storageBucket: 'raccoon-doctor-3f2e3.appspot.com',
    measurementId: 'G-K1C7PLTDY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo4TH1E-MpuJKrKT60kDjcZmek4qlV3nk',
    appId: '1:734003181340:android:1b4703188e6152ff9eecd9',
    messagingSenderId: '734003181340',
    projectId: 'raccoon-doctor-3f2e3',
    storageBucket: 'raccoon-doctor-3f2e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzY8sSk5buht2rXaJOJTWOdIB22ZiXZPs',
    appId: '1:734003181340:ios:d1cb3c55e3825c8a9eecd9',
    messagingSenderId: '734003181340',
    projectId: 'raccoon-doctor-3f2e3',
    storageBucket: 'raccoon-doctor-3f2e3.appspot.com',
    iosClientId: '734003181340-1nkndvs8j5hqjai9q7srcums7a7idtmp.apps.googleusercontent.com',
    iosBundleId: 'com.example.raccoonDoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzY8sSk5buht2rXaJOJTWOdIB22ZiXZPs',
    appId: '1:734003181340:ios:d1cb3c55e3825c8a9eecd9',
    messagingSenderId: '734003181340',
    projectId: 'raccoon-doctor-3f2e3',
    storageBucket: 'raccoon-doctor-3f2e3.appspot.com',
    iosClientId: '734003181340-1nkndvs8j5hqjai9q7srcums7a7idtmp.apps.googleusercontent.com',
    iosBundleId: 'com.example.raccoonDoctor',
  );
}
